version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'anwfi'   
      MYSQL_USER: 'sotatek'
      MYSQL_PASSWORD: 'Sotatek2021'      
      MYSQL_ROOT_PASSWORD: 'Sotatek2021'
    ports:
      - '3366:3306'
    expose:
      - '3366'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6366:6379"
    volumes:
      - ./redis:/data
volumes:
  mysql:
    driver: local
  redis:
    driver: local